apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common-cronjob.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "common-cronjob.labels" . | nindent 4 }}