apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: $(APPSET_NAME)
  namespace: argocd
  labels:
    custom.kubernetes.io/is-adhoc: "true"
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/nixonjoshua98/nixon-gitops.git
              revision: main
              files:
                - path: "$(ARGO_FILE_PATH)"
          - list:
              elementsYaml: "{{ .components | toJson }}"
  template:
    metadata:
      name: "{{ .name }}-{{ .environment }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "$(MANIFEST_GENERATE_PATHS)"
    spec:
      project: default
      source:
        repoURL: https://github.com/nixonjoshua98/nixon-gitops.git
        targetRevision: main
        path: "{{ .chart }}"
        helm:
          releaseName: "{{ .name }}-{{ .environment }}"
          ignoreMissingValueFiles: false
          valueFiles: $(VALUE_FILES)
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            custom.kubernetes.io/require-image-registry-secret: "true"
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Prune=confirm
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
