apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.repositorySecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "nixon-argocd-resources.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secretStore.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.repositorySecret.vaultName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.repositorySecret.name }}
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        depth: "1"
        type: "git"
        url: "https://github.com/nixonjoshua98/nixon-gitops.git"
        username: "nixonjoshua98"
        password: "{{ `{{ .PASSWORD }}` }}"
  data:
    - secretKey: PASSWORD
      remoteRef:
        key: ARGOCD-GITHUB-PASSWORD