{{- range .Values.clusterSecretStores }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .name }}
  labels:
{{ include "cluster-resources.labels" $ | indent 4 }}
spec:
  provider:
    azurekv:
      vaultUrl: {{ .vaultUrl }}
      tenantId: {{ .tenantId }}
      authSecretRef:
        clientId:
          name: {{ .credentialsSecretName }}
          namespace: external-secrets
          key: CLIENT_ID
        clientSecret:
          name: {{ .credentialsSecretName }}
          namespace: external-secrets
          key: CLIENT_SECRET
{{- end }}
