{{- with .Values.externalSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{- include "common-deployable.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $.Values.secretStore.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .name }}
    creationPolicy: Owner
  data:
{{- range .values }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRefKey }}
{{- end }}
{{- end }}
