{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
	name: {{ include "common-deployable.name" . }}
	namespace: {{ .Release.Namespace }}
	labels:
{{- include "common-deployable.labels" . | nindent 4 }}
spec:
	namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
	selector:
		matchLabels:
{{- include "common-deployable.selectorLabels" . | nindent 6 }}
	endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
{{- end }}
