{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common-deployable.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "common-deployable.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
{{- include "common-deployable.selectorLabels" . | nindent 4 }}
  ports:
{{- range $name, $port := .Values.service.defaultPorts }}
    - name: {{ $name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: {{ $port.protocol }}
{{- end }}
{{- end }}