repositories:
  - name: hcloud
    url: https://charts.hetzner.cloud
  - name: jetstack
    url: https://charts.jetstack.io
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: traefik
    url: https://traefik.github.io/charts

helmDefaults:
  historyMax: 1

releases:
  - name: nixon-netbird-resources
    namespace: netbird
    chart: ../charts/nixon-netbird-resources
    values:
      - ../configuration/base/values.yaml
    needs:
      - netbird/netbird-operator
      - external-secrets/external-secrets

  - name: nixon-external-secrets-resources
    namespace: external-secrets
    chart: ../charts/nixon-external-secrets-resources
    values:
      - ../configuration/base/values.yaml
    needs:
      - external-secrets/external-secrets

  - name: nixon-cluster-resources
    namespace: default
    chart: ../charts/nixon-cluster-resources
    values:
      - ../configuration/base/values.yaml
    needs:
      - cert-manager/cert-manager
      - external-secrets/nixon-external-secrets-resources

  - name: nixon-argocd-resources
    namespace: argocd
    chart: ../charts/nixon-argocd-resources
    values:
      - ../configuration/base/values.yaml
    needs:
      - argocd/argocd
      - external-secrets/nixon-external-secrets-resources

  - name: netbird-operator
    namespace: netbird
    chart: oci://ghcr.io/netbirdio/helm-charts/netbird-operator
    version: 0.8.0
    values:
      - values/netbird-operator.yaml
    needs:
      - cert-manager/cert-manager

  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: 10.3.0
    values:
      - values/argocd.yaml

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.21.0
    values:
      - values/cert-manager.yaml
    needs:
      - monitoring/kube-prometheus-stack

  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: 41.1.0
    values:
      - values/traefik.yaml

  - name: external-secrets
    namespace: external-secrets
    chart: external-secrets/external-secrets
    version: 2.8.0
    values:
      - values/external-secrets.yaml
    needs:
      - cert-manager/cert-manager

  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 88.1.5
    values:
      - values/prometheus.yaml

  # - name: loki
  #   namespace: monitoring
  #   chart: grafana/loki
  #   version: 6.49.0
  #   values:
  #     - values/grafana-loki.yaml

  # - name: alloy
  #   namespace: monitoring
  #   chart: grafana/alloy
  #   version: 1.5.0
  #   needs:
  #     - monitoring/loki
  #   values:
  #     - values/grafana-alloy.yaml

  - name: cnpg
    namespace: cnpg-system
    chart: cnpg/cloudnative-pg
    version: 0.29.0
    needs:
      - cert-manager/cert-manager

  - name: cnpg-barman-cloud
    namespace: cnpg-system
    chart: cnpg/plugin-barman-cloud
    version: 0.7.0
    needs:
      - cnpg-system/cnpg
      - cert-manager/cert-manager

  - name: hcloud-ccm
    namespace: kube-system
    chart: hcloud/hcloud-cloud-controller-manager
    version: 1.34.0
    values:
      - values/hcloud-ccm.yaml

  - name: hcloud-csi
    namespace: kube-system
    chart: hcloud/hcloud-csi
    version: 2.22.0
