appSetValues:
  - APPSET_NAME: greedymercs-appset
    ARGO_FILE_PATH: argocd/workloads/greedymercs-*.yaml
    VALUE_FILES:
      - /configuration/greedymercs/environments/{{ .environment }}/values.yaml
      - /configuration/greedymercs/environments/{{ .environment }}/{{ .name }}.yaml

  - APPSET_NAME: tier9-appset
    ARGO_FILE_PATH: argocd/workloads/tier9-*.yaml
    VALUE_FILES:
      - /configuration/tier9/environments/{{ .environment }}/values.yaml
      - /configuration/tier9/environments/{{ .environment }}/{{ .name }}.yaml

  - APPSET_NAME: untitledproject-appset
    ARGO_FILE_PATH: argocd/workloads/untitledproject-*.yaml
    VALUE_FILES:
      - /configuration/untitledproject/environments/{{ .environment }}/values.yaml
      - /configuration/untitledproject/environments/{{ .environment }}/{{ .name }}.yaml
