apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ .Values.imagePullSecret }}
  labels:
{{ include "nixon-cluster-resources.labels" . | indent 4 }}
spec:
  externalSecretName: {{ .Values.imagePullSecret }}
  
  refreshTime: {{ .Values.secretStore.refreshInterval }}
  
  namespaceSelectors:
    - matchLabels:
        custom.kubernetes.io/require-image-registry-secret: 'true'

  externalSecretSpec:
    secretStoreRef:
      name: {{ .Values.secretStore.name }}
      kind: ClusterSecretStore
    refreshInterval: {{ .Values.secretStore.refreshInterval }}
    target:
      template:
        type: kubernetes.io/dockerconfigjson
      name: {{ .Values.imagePullSecret }}
      creationPolicy: Owner
    data:
      - secretKey: .dockerconfigjson
        remoteRef:
          key: ACR-PULL-SECRET