apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: untitledproject-appset
  namespace: argocd
  labels:
    custom.kubernetes.io/is-adhoc: "true"
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/nixonjoshua98/nixon-gitops.git
              revision: main
              files:
                - path: "argocd/workloads/untitledproject-*.yaml"
          - list:
              elementsYaml: "{{ .components | toJson }}"
  template:
    metadata:
      name: "{{ .name }}-{{ .environment }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "/charts/common-deployable;/charts/cnpg-cluster;/argocd/workloads/untitledproject-*.yaml;/configuration/base/values.yaml;/configuration/untitledproject/environments/{{ .environment }}/values.yaml;/configuration/untitledproject/environments/{{ .environment }}/{{ .name }}.yaml"
    spec:
      project: default
      source:
        repoURL: https://github.com/nixonjoshua98/nixon-gitops.git
        targetRevision: main
        path: "{{ .chart }}"
        helm:
          releaseName: "{{ .name }}-{{ .environment }}"
          ignoreMissingValueFiles: false
          valueFiles: ["/configuration/base/values.yaml", "/configuration/untitledproject/environments/{{ .environment }}/values.yaml", "/configuration/untitledproject/environments/{{ .environment }}/{{ .name }}.yaml"]
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            custom.kubernetes.io/require-image-registry-secret: "true"
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Prune=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
