apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nixon-cronjob.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "nixon-cronjob.labels" . | nindent 4 }}