apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.credentialSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "nixon-netbird-resources.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secretStore.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.credentialSecret.name }}
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_TOKEN
      remoteRef:
        key: NETBIRD-TOKEN