name: GreedyMercs

on:
  repository_dispatch:
    types:
      - gm.api.monolith
      - gm.discordbot


permissions:
  contents: write

jobs:
  patch-image:
    uses: ./.github/workflows/Template.Deployment.yaml
    with:
      project: greedymercs
      environment: ${{ github.event.client_payload.environment }}
      action: ${{ github.event.action }}
      image: ${{ github.event.client_payload.image }}
