name: HelmReleaseChecker

on:
  push:
    branches:
      - main
    paths:
      - source/helm-release-checker/**
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    uses: nixonjoshua98/shared-workflows/.github/workflows/Template.Build.Docker.ACR.yaml@master
    with:
      azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ vars.AZURE_SUB_ID }}
      image_registry: ${{ vars.AZURE_REGISTRY }}
      image_repository: "helm-release-checker"
      dockerfile_path: "./source/helm-release-checker/Dockerfile"
      build_context: "./source/helm-release-checker"
    secrets: inherit

  deploy:
    needs:
      - build
    uses: ./.github/workflows/Template.UpdateImage.yaml
    with:
      file_path: "configuration/cluster/helm-release-checker.yaml"
      image: ${{ needs.build.outputs.image }}
    secrets: inherit
