name: Koruxa

on:
  repository_dispatch:
    types:
      - koruxa.discordbot

permissions:
  contents: write

jobs:
  patch-image:
    uses: ./.github/workflows/Template.UpdateImage.yaml
    with:
      project: koruxa
      environment: ${{ github.event.client_payload.environment }}
      action: ${{ github.event.action }}
      image: ${{ github.event.client_payload.image }}
