name: Template.UpdateImage

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string

      project:
        required: false
        type: string

      action:
        required: false
        type: string

      file_path:
        required: false
        type: string

      image:
        required: true
        type: string

permissions:
  contents: write

concurrency:
  group: template-update-deployment-image
  cancel-in-progress: false

jobs:
  patch:
    runs-on: ubuntu-latest
    env:
      PROJECT: ${{ inputs.project }}
      ENVIRONMENT: ${{ inputs.environment }}
      ACTION: ${{ inputs.action }}
      FILE_PATH: ${{ inputs.file_path }}
      IMAGE: ${{ inputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Resolve target file path
        run: |
          if [[ -n "$FILE_PATH" ]]; then
            FILE_PATH_LOWER="$FILE_PATH"
          else
            FILE_PATH_LOWER="configuration/${PROJECT,,}/environments/${ENVIRONMENT,,}/$(echo "${ACTION,,}" | tr '.' '-').yaml"
          fi

          echo "FILE_PATH_LOWER=${FILE_PATH_LOWER}" >>${GITHUB_ENV}

      - name: Update image
        run: |
          sed -i "s|^image:.*|image: \"$IMAGE\"|" "$FILE_PATH_LOWER"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add "$FILE_PATH_LOWER"

          git commit -m "chore: Updated ${FILE_PATH_LOWER}" || echo "No changes to commit"
          git pull --rebase origin
          git push
