name: UntitledProject

on:
  repository_dispatch:
    types:
      - untitledproject.api.monolith
      - untitledproject.api.auth


permissions:
  contents: write

jobs:
  patch-image:
    uses: ./.github/workflows/Template.Deployment.yaml
    with:
      project: untitledproject
      environment: ${{ github.event.client_payload.environment }}
      action: ${{ github.event.action }}
      image: ${{ github.event.client_payload.image }}
