apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "cnpg-cluster.clusterName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cnpg-cluster.labels" . | indent 4 }}
spec:
  instances: {{ .Values.cluster.instances }}
  imageName: ghcr.io/cloudnative-pg/postgresql:{{ .Values.cluster.image.tag }}

  bootstrap:
  {{ if eq .Values.bootstrap.mode "initdb" }}
    initdb:
      database: {{ .Values.cluster.databaseName }}
      owner: {{ .Values.superUser.name }}
      secret:
        name: {{ include "cnpg-cluster.userSecretName" (dict "root" . "name" .Values.superUser.name) }}
  {{ else }}
    recovery:
      source: external-cluster
      database: {{ .Values.cluster.databaseName }}
      owner: {{ .Values.superUser.name }}
  {{ end }}

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist

  superuserSecret: 
    name: {{ include "cnpg-cluster.userSecretName" (dict "root" . "name" .Values.superUser.name) }}

  managed:
    services:
      disabledDefaultServices: ['ro', 'r']
{{- if .Values.managedUsers }}
    roles:
{{- range .Values.managedUsers }}
      - name: {{ .name }}
        ensure: present
        login: true
        passwordSecret:
          name: {{ include "cnpg-cluster.userSecretName" (dict "root" $ "name" .name) }}
{{- end }}
{{- end }}

  {{ if ne .Values.bootstrap.mode "initdb" }}
  externalClusters:
    - name: external-cluster
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: {{ include "cnpg-cluster.externalObjectStore" . }}
          serverName: {{ .Values.externalObjectStore.serverName }}
  {{ end }}

  postgresql:     
    parameters:
      pg_stat_statements.max: '1000'
      huge_pages: 'off'
      log_timezone: 'Etc/UTC'
      log_min_duration_statement: '200'
      datestyle: 'iso, dmy'
      timezone: 'Etc/UTC'
      effective_io_concurrency: '200'
{{- range $key, $value := .Values.cluster.parameters }}
      {{ $key }}: {{ $value | quote }}
{{- end }}

  {{ if .Values.resources -}}
  resources: {{- toYaml .Values.resources | nindent 4 }}
  {{- end }}

  enableSuperuserAccess: true
    
{{ if .Values.objectStore.enabled }}
  plugins:       
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      isWALArchiver: true
      parameters:
        barmanObjectName: {{ include "cnpg-cluster.objectStore" . }}
{{- end }}

  storage:
    storageClass: local-path
    size: 1Gi
