{{ if .Values.objectStore.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "cnpg-cluster.objectStore" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cnpg-cluster.labels" $ | indent 4 }}
spec:
  refreshInterval: {{ .Values.secretStore.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ include "cnpg-cluster.objectStore" . }}
    creationPolicy: Owner
  data:
    - secretKey: CONNECTION_STRING
      remoteRef:
        key: {{ .Values.objectStore.secretStoreKey }}
{{- end }}