{{ if .Values.objectStore.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "cnpg-cluster.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cnpg-cluster.labels" $ | indent 4 }}
spec:
  method: plugin
  immediate: true
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  schedule: '0 0 0 */1 * *'
  backupOwnerReference: cluster
  cluster:
    name: {{ include "cnpg-cluster.clusterName" . }}
{{- end }}