{{- $superUserList := list .Values.superUser -}}

{{- $allUsers := concat $superUserList .Values.managedUsers -}}

{{- range $allUsers }}
---
{{ if .password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cnpg-cluster.userSecretName" (dict "root" $ "name" .name) }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "cnpg-cluster.labels" $ | indent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .name | quote }}
  password: {{ .password | quote }}
{{ else }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "cnpg-cluster.userSecretName" (dict "root" $ "name" .name) }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "cnpg-cluster.labels" $ | indent 4 }}
spec:
  refreshInterval: {{ $.Values.secretStore.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ include "cnpg-cluster.userSecretName" (dict "root" $ "name" .name) }}
    creationPolicy: Owner
    template:
      data:
        username: {{ .name }}
        password: '{{ "{{ .PASSWORD }}" }}'
  data:
    - secretKey: PASSWORD
      remoteRef:
        key: {{ .externalPasswordRef }}
{{ end }}
{{- end }}
