{{- range .Values.databaseRoles }}
{{ $resourceName := include "nixon-cnpg-cluster.userResourceName" (dict "root" $ "name" .name) }}
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: {{ $resourceName }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "nixon-cnpg-cluster.labels" $ | indent 4 }}
spec:
  cluster:
    name: {{ include "nixon-cnpg-cluster.name" $ }}
  name: {{ .name }}
  login: true
  superuser: false
  createdb: false
  databaseRoleReclaimPolicy: delete
  passwordSecret:
    name: {{ $resourceName }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $resourceName }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "nixon-cnpg-cluster.labels" $ | indent 4 }}
spec:
  refreshInterval: {{ $.Values.secretStore.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ $resourceName }}
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: {{ .name }}
        password: '{{ "{{ .PASSWORD }}" }}'
  data:
    - secretKey: PASSWORD
      remoteRef:
        key: {{ .passwordRemoteRefKey }}
---
{{- end }}