{{ if .Values.objectStore.enabled }}
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ include "nixon-cnpg-cluster.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "nixon-cnpg-cluster.labels" $ | indent 4 }}
spec:
  retentionPolicy: 7d
  configuration:
    data:
      compression: bzip2
    wal:
      compression: bzip2
    destinationPath: {{ .Values.objectStore.destinationPath | quote }}
    azureCredentials:
      inheritFromAzureAD: true
{{- end }}