{{ if .Values.postgresUserPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nixon-cnpg-cluster.postgresPasswordSecret" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    cnpg.io/reload: "true"
{{ include "nixon-cnpg-cluster.labels" $ | indent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: {{ .Values.postgresUserPassword | quote }}
{{- end }}
