containerPorts:
  http:
    enabled: true
  metrics:
    enabled: true

service:
  enabled: true
  ports:
    http:
      enabled: true
    metrics:
      enabled: true

readinessProbe:
  enabled: true

serviceMonitor:
  enabled: true
