

- name: Ensure used directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ k3s_binary_path | dirname }}"
    - "{{ k3s_installer_path | dirname }}"
    - "{{ k3s_binary_install_path | dirname }}"

  # Install script is used for every node
  # We only download this once, so if it changes then we won't get any changes
  # unless we explicitly re-download it.

- name: Download k3s install script
  ansible.builtin.get_url:
    url: "{{ k3s_installer_url }}"
    dest: "{{ k3s_installer_path }}"
    mode: "0755"
    force: false

- name: Check if k3s version binary is already downloaded
  ansible.builtin.stat:
    path: "{{ k3s_binary_path }}"
  register: k3s_binary_path_stat

  # Download the binary, we store them in a download path
  # then copy them into the install location. We do
  # this mainly for visability. 

- name: Download k3s binary
  when: not k3s_binary_path_stat.stat.exists
  ansible.builtin.get_url:
    url: "{{ k3s_binary_url }}"
    dest: "{{ k3s_binary_path }}"
    mode: "0755"
    force: false

  # controlplane_host (which is used to generate k3s_url) is not neede
  # for the init controlplane, so I attempted to add a when predicate
  # to exclude it - But it would error saying it was undefined regardless.

- name: Set controlplane_host fact
  block:
    - name: Find cluster init controlplane
      ansible.builtin.set_fact:
        controlplane_host: "{{ item }}"
      loop: "{{ groups['controlplane'] }}"
      when: hostvars[item]['is_cluster_initialiser'] | default(false) | bool

    - name: Set controlplane_host fallback
      ansible.builtin.set_fact:
        controlplane_host: "{{ groups['controlplane'][0] }}"
      when: controlplane_host is not defined

    - name: Verify controlplane_host is defined
      ansible.builtin.assert:
        that:
          - controlplane_host is defined
          - controlplane_host | length > 0
        fail_msg: "Failed to determine controlplane_host"

  # The k3s_url is used for all nodes, besides the init-cluster node
  # We ideally use the bootstrapper node but then fallback to the first controlplane
  # in the list. With assertions to prevent issues.

- name: Set k3s_url fact
  ansible.builtin.set_fact:
    k3s_url: "https://{{ controlplane_host }}:6443"

  # The cluster token is needed for all nodes, besides the node which is
  # used to init the cluster itself.
  # The controlplane_host is created above.

- name: Fetch k3s_token
  when: not (is_cluster_initialiser | default(false) | bool)
  block:
    - name: Fetch k3s_token
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: _k3s_token
      when: controlplane_host is defined
      delegate_to: "{{ controlplane_host }}"

    - name: Set k3s_token fact
      ansible.builtin.set_fact:
        k3s_token: "{{ _k3s_token.content | b64decode | trim }}"    

    - name: Verify k3s_token is defined
      ansible.builtin.assert:
        that:
          - k3s_token is defined
          - k3s_token | length > 0
        fail_msg: "Failed to determine k3s_token"  

  # The binary will already exist, unless its a new node or we are bumping the version
  # Regardless, we copy it over. This is still quicker than re-downloading it for every iteration.

- name: Copy K3s binary to install path
  ansible.builtin.copy:
    src: "{{ k3s_binary_path }}"
    dest: "{{ k3s_binary_install_path }}"
    mode: "0755"
    remote_src: true

  # Include the relevant node type task
  # Most notebly, generates the k3s_install_command fact.

- name: Include 'controlplane.yaml'
  include_tasks: controlplane.yaml
  when: node_type == 'controlplane'

- name: Include 'agent.yaml'
  include_tasks: agent.yaml
  when: node_type == 'agent'

  # Executes the generates install command
  # We log and writes the install command to file so its easier to debug
  # The file itself hold no value in the installation process.

- name: Execute k3s install
  when: k3s_install_command is defined
  block:
    - name: Execute the k3s install command
      ansible.builtin.shell: "{{ k3s_install_command }}"
      register: k3s_install_output
      changed_when: true

    - name: Debug the k3s install output
      ansible.builtin.debug:
        var: k3s_install_output.stdout_lines

    - name: Write install command to a file
      ansible.builtin.copy:
        content: "{{ k3s_install_command }}"
        dest: /tmp/k3s-install-command