{{- range .Values.clusterSecretStores }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    azure.workload.identity/use: "true"
{{ include "nixon-external-secrets-resources.labels" $ | indent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ $.Values.azureCredential.clientId | quote }}
{{- end }}
