{{- range .Values.clusterSecretStores }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .name }}
  labels:
{{ include "nixon-external-secrets-resources.labels" $ | indent 4 }}
spec:
  provider:
    azurekv:
      vaultUrl: {{ .vaultUrl }}
      tenantId: {{ $.Values.azureCredential.tenantId | quote }}
      authType: WorkloadIdentity
      serviceAccountRef:
        name: {{ .name }}
        namespace: {{ $.Release.Namespace }}
{{- end }}
