environment: production

namespace: greedymercs-production

components:
  - name: greedymercs-api-monolith
    chart: charts/nixon-deployable

  - name: greedymercs-postgresql
    chart: charts/nixon-cnpg-cluster
