environment: production

namespace: tier9-production

components:
  - name: tier9-abo-api
    chart: charts/common-deployable

  - name: tier9-abo-slime
    chart: charts/common-deployable

  - name: tier9-abo-worldchat
    chart: charts/common-deployable

  - name: tier9-postgresql
    chart: charts/cnpg-cluster
