environment: devtest

namespace: untitledproject-devtest

components:
  - name: untitledproject-api-monolith
    chart: charts/nixon-deployable

  - name: untitledproject-api-auth
    chart: charts/nixon-deployable

  - name: untitledproject-postgresql
    chart: charts/nixon-cnpg-cluster
